name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastapi_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d fastapi_test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/fastapi_test_db
        run: pytest -v
      # Node setup (Playwright frontend tests)
      # -------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Install frontend dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # -------------------------
      # Start FastAPI server
      # -------------------------
      - name: Start FastAPI server
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      # -------------------------
      # Start frontend server
      # -------------------------
      - name: Start frontend server
        run: |
          npx http-server ./frontend -p 8080 &
          sleep 5

      # -------------------------
      # Run Playwright tests
      # -------------------------
      - name: Run Playwright E2E tests
        run: npx playwright test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/user_calculation_routes:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/user_calculation_routes:module-13